In [92]:
#%pip install pandas numpy

In [93]:
import os
import pandas as pd 
import numpy as np

In [94]:
# Path to datasets to be cleaned !! CHANGE THIS TO MAKE THE SCRIPT RUNNING !! 
path = "/Users/gabrielebuoso/Desktop/dataset/"
path1 = "C:\\Users\\andre\\Desktop\\Dati_Tweb\\"
path2 = "C:\\Users\\andre\\Desktop\\Dati_Tweb\\aggiuntivi\\"

In [ ]:
try:
    df_actors=pd.read_csv(path1 + "actors.csv")
    df_countries=pd.read_csv(path1 + "countries.csv")
    df_crew=pd.read_csv(path1 + "crew.csv")
    df_genres=pd.read_csv(path1 + "genres.csv")
    df_languages=pd.read_csv(path1 + "languages.csv")
    df_movies=pd.read_csv(path1 + "movies.csv")
    df_posters=pd.read_csv(path1 + "posters.csv")
    df_releases=pd.read_csv(path1 + "releases.csv")
    df_studios=pd.read_csv(path1 + "studios.csv")
    df_themes=pd.read_csv(path1 + "themes.csv")
    df_tomatoes=pd.read_csv(path2 + "rotten_tomatoes_reviews.csv")
    df_oscars=pd.read_csv(path2 + "the_oscar_awards.csv")
except Exception as e:
    print(e)

# **Data Cleaning**

## Pulizia Actors

In [96]:
df_actors.shape

(5798450, 3)

In [97]:
df_actors.rename(columns={'id': 'id_film'}, inplace=True)
df_actors['name']=df_actors['name'].astype("str")
df_actors.dtypes

id_film     int64
name       object
role       object
dtype: object

In [98]:
df_actors.head()

   id_film               name    role
0  1000001      Margot Robbie  Barbie
1  1000001       Ryan Gosling     Ken
2  1000001    America Ferrera  Gloria
3  1000001  Ariana Greenblatt   Sasha
4  1000001           Issa Rae  Barbie

In [99]:
df_actors.isna().sum()
df_actors.fillna({"role":"Extra"},inplace=True)

Controllo dei valori duplicati

In [100]:
df_actors.duplicated().sum()

np.int64(946)

In [101]:
#rimozione dei duplicati
df_actors.drop_duplicates(inplace=True)
df_actors.duplicated().sum()
df_actors.reset_index(drop=True,inplace=True)

In [102]:
df_actors.shape

(5797504, 3)

## Pulizia Countries

In [103]:
df_countries.shape

(693476, 2)

In [104]:
df_countries.dtypes

id          int64
country    object
dtype: object

In [105]:
df_countries.rename(columns={'id': 'id_film'}, inplace=True)

df_countries.dtypes

id_film     int64
country    object
dtype: object

In [106]:
df_countries.isna().sum()

id_film    0
country    0
dtype: int64

In [107]:
df_countries.duplicated().sum()

np.int64(0)

## Pulizia Crew

In [108]:
df_crew.shape

(4720183, 3)

In [109]:
df_crew.rename(columns={'id': 'id_film'}, inplace=True)
df_crew.dtypes

id_film     int64
role       object
name       object
dtype: object

In [110]:
#Viene trovato un valore null come nome
df_crew.loc[df_crew['name'].isna(), "name"] = "Unknown"

## Pulizia Genres

In [111]:
df_genres.shape

(1046849, 2)

In [112]:
df_genres.rename(columns={'id': 'id_film'}, inplace=True)

df_genres.dtypes

id_film     int64
genre      object
dtype: object

In [113]:
df_genres.isna().sum()

id_film    0
genre      0
dtype: int64

In [114]:
df_genres["genre"].unique()

array(['Comedy', 'Adventure', 'Thriller', 'Drama', 'Science Fiction',
       'Action', 'Music', 'Romance', 'History', 'Crime', 'Animation',
       'Mystery', 'Horror', 'Family', 'Fantasy', 'War', 'Western',
       'TV Movie', 'Documentary'], dtype=object)

In [115]:
df_genres.duplicated().sum()

np.int64(0)

## Pulizia Languages

In [116]:
df_languages.shape

(1038762, 3)

In [117]:
df_languages.rename(columns={'id': 'id_film'}, inplace=True)
df_languages.dtypes

id_film      int64
type        object
language    object
dtype: object

In [118]:
df_languages.isna().sum()

id_film     0
type        0
language    0
dtype: int64

In [119]:
df_languages["language"] = df_languages["language"].replace('Persian\xa0(Farsi)', 'Persian (Farsi)')
df_languages["language"] = df_languages["language"].replace('Hebrew\xa0(modern)', 'Hebrew (modern)')
df_languages["language"] = df_languages["language"].replace('Greek\xa0(modern)', 'Greek (modern)')
df_languages["language"] = df_languages["language"].replace('Tonga\xa0(Tonga Islands)', 'Tonga (Tonga Islands)')
df_languages["language"] = df_languages["language"].replace('Old Church Slavonic,\xa0Church Slavonic,\xa0Old Bulgarian', 'Old Church Slavonic, Church Slavonic, Old Bulgarian')

df_languages["language"].unique()

array(['English', 'Korean', 'German', 'Cantonese', 'Chinese', 'Dutch',
       'Spanish', 'French', 'Japanese', 'Swedish', 'Swahili',
       'Portuguese', 'Hindi', 'Italian', 'Tagalog', 'Xhosa', 'Latin',
       'Russian', 'Finnish', 'Hungarian', 'Somali', 'Romanian',
       'Vietnamese', 'Turkish', 'Czech', 'Estonian', 'Persian (Farsi)',
       'Urdu', 'Arabic', 'Polish', 'Hebrew (modern)', 'Greek (modern)',
       'Yiddish', 'Norwegian', 'Haitian, Haitian Creole', 'Khmer',
       'Nepali', 'Akan', 'Icelandic', 'Malay',
       'Eastern Punjabi, Eastern Panjabi', 'Georgian', 'Indonesian',
       'Belarusian', 'Danish', 'Tamil', 'Sinhalese, Sinhala',
       'Tibetan Standard, Tibetan, Central', 'Armenian', 'Thai', 'Telugu',
       'Scottish Gaelic, Gaelic', 'Northern Sami', 'Esperanto',
       'Bulgarian', 'Afrikaans', 'Chichewa, Chewa, Nyanja',
       'Southern Sotho', 'Zulu', 'Irish', 'Breton', 'Croatian',
       'Bengali, Bangla', 'Welsh', 'Navajo, Navaho', 'Albanian',
       'Inuktitut', 'Catalan', 'Quechua', 'Azerbaijani', 'Samoan',
       'Ukrainian', 'Mongolian', 'Māori', 'Tatar', 'Mayan',
       'Fula, Fulah, Pulaar, Pular', 'Slovak', 'Lithuanian', 'Cree',
       'Lao', 'Galician', 'Amharic', 'Serbian', 'Moldavian',
       'Serbo-Croatian', 'Cornish', 'Wolof', 'Pashto, Pushto', 'Twi',
       'Corsican', 'Bambara', 'Sanskrit (Saṁskṛta)', 'Macedonian',
       'Burmese', 'Maltese', 'Bosnian', 'No spoken language', 'Marathi',
       'Ido', 'Guaraní', 'Kurdish', 'Ganda', 'Hausa', 'Tahitian',
       'Latvian', 'Lingala', 'Gujarati', 'Malayalam', 'Basque',
       'Javanese', 'Tswana', 'Sundanese', 'Kinyarwanda', 'Kirundi',
       'Afar', 'Dzongkha', 'Tola', 'Kannada', 'Uzbek', 'Ojibwe, Ojibwa',
       'Igbo', 'Ewe', 'Pāli', 'Chechen', 'Kashmiri', 'Oromo',
       'Kalaallisut, Greenlandic', 'Tajik', 'Slovene', 'Aymara',
       'Sardinian', 'Assamese', 'Ossetian, Ossetic', 'Occitan', 'Avaric',
       'Bislama', 'Kyrgyz', 'Kazakh', 'Aragonese', 'Yolngu matha',
       'Malagasy', 'Gibberish', 'Kikuyu, Gikuyu', 'Yoruba', 'Maithili',
       'Uyghur', 'Sango', 'Nuosu', 'Hiri Motu', 'Kongo',
       'Tonga (Tonga Islands)', 'Shona', 'Luxembourgish, Letzeburgesch',
       'Sindhi', 'Chuvash', 'Fijian', 'Mari', 'Walloon', 'Abkhaz',
       'Inupiaq', 'Turkmen', 'Faroese', 'Marshallese', 'Romansh',
       'Western Frisian', 'Norwegian Bokmål', 'Oriya',
       'Old Church Slavonic, Church Slavonic, Old Bulgarian', 'Herero',
       'Southern Ndebele', 'Tigrinya', 'Ndonga',
       'Limburgish, Limburgan, Limburger', 'Swati', 'Norwegian Nynorsk',
       'Bashkir', 'Interlingue', 'Manx', 'Nauruan',
       'Divehi, Dhivehi, Maldivian', 'Venda', 'Interlingua',
       'Northern Ndebele', 'Chamorro', 'Zhuang, Chuang', 'Luba-Katanga',
       'Kwanyama, Kuanyama', 'Tsonga', 'Komi', 'Avestan', 'Volapük'],
      dtype=object)

In [120]:
df_languages.duplicated().sum()

np.int64(0)

## Pulizia Movies

In [121]:
df_movies.shape

(941597, 7)

In [122]:
df_movies.dtypes

id               int64
name            object
date           float64
tagline         object
description     object
minute         float64
rating         float64
dtype: object

In [123]:
df_movies.head(200)

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09
...,...,...,...,...,...,...,...
195,1000196,Tangled,2010.0,They're taking adventure to new lengths.,When the kingdom's most wanted-and most charmi...,100.0,3.93
196,1000197,Thor: Love and Thunder,2022.0,The one is not the only.,After his retirement is interrupted by Gorr th...,119.0,2.48
197,1000198,Jaws,1975.0,Don't go in the water,When an insatiable great white shark terrorize...,124.0,3.96
198,1000199,The Departed,2006.0,Lies. Betrayal. Sacrifice. How far will you ta...,"To take down South Boston's Irish Mafia, the p...",151.0,4.31
199,1000200,Avengers: Age of Ultron,2015.0,A New Age Has Come.,When Tony Stark tries to jumpstart a dormant p...,141.0,3.10

In [124]:
df_movies.isna().sum()

id                  0
name               10
date            91913
tagline        802210
description    160812
minute         181570
rating         850598
dtype: int64

In [125]:
df_movies.dropna(subset=["name", "date", "tagline", "description", "minute", "rating"], how='all', inplace=True)
df_movies.shape

(941591, 7)

In [126]:
df_movies.columns
df_releases

              id    country        date        type rating
0        1000001    Andorra  2023-07-21  Theatrical    NaN
1        1000001  Argentina  2023-07-20  Theatrical    ATP
2        1000001  Australia  2023-07-19  Theatrical     PG
3        1000001  Australia  2023-10-01     Digital     PG
4        1000001    Austria  2023-07-20  Theatrical    NaN
...          ...        ...         ...         ...    ...
1332777  1940967        USA  1909-01-01  Theatrical    NaN
1332778  1940968     Sweden  1908-11-11  Theatrical    NaN
1332779  1940969     France  1902-01-01  Theatrical    NaN
1332780  1940970     France  1902-01-01  Theatrical    NaN
1332781  1940971     France  1902-01-01  Theatrical    NaN

[1332782 rows x 5 columns]

In [127]:
# we will split analysis in two different stories!
df_released_movies = df_movies[df_movies['id'].isin(df_releases['id'])]
df_unreleased_movies = df_movies[~df_movies['id'].isin(df_releases['id'])]

In [128]:
df_released_movies["rating"].isna().sum()

np.int64(738954)

In [129]:
df_test=df_released_movies.loc[df_released_movies["date"].isna()]
df_test.shape

(142, 7)

In [130]:
# Rimuovere i film che non hanno valori nel campo "name" e neanche nel campo "description"
# perchè è presente un film dal "name" NaN che quindi immagino sia un effettivo film
df_released_movies = df_released_movies.dropna(subset=['name', 'description'], how='all').reset_index(drop=True)

In [131]:
#assenza di duplicati 
df_released_movies.duplicated().sum()

np.int64(0)

In [132]:
df_released_movies

,id,name,date,tagline,description,minute,rating
0,1000001,Barbie,2023.0,She's everything. He's just Ken.,Barbie and Ken are having the time of their li...,114.0,3.86
1,1000002,Parasite,2019.0,Act like you own the place.,"All unemployed, Ki-taek's family takes peculia...",133.0,4.56
2,1000003,Everything Everywhere All at Once,2022.0,The universe is so much bigger than you realize.,An aging Chinese immigrant is swept up in an i...,140.0,4.30
3,1000004,Fight Club,1999.0,Mischief. Mayhem. Soap.,A ticking-time-bomb insomniac and a slippery s...,139.0,4.27
4,1000005,La La Land,2016.0,Here's to the fools who dream.,"Mia, an aspiring actress, serves lattes to mov...",129.0,4.09
...,...,...,...,...,...,...,...
826012,1940967,A Nursery In Paris,1909.0,NaN,Short film showing a nursery.,2.0,NaN
826013,1940968,I klädloge och på scen,1908.0,NaN,Miss Inga Berentz dresses up for the entrance....,7.0,NaN
826014,1940969,Danse fantaisiste,1902.0,NaN,"""Danse fantaisiste"" (Gaumont #589) is part of ...",NaN,NaN
826015,1940970,La Gigue,1902.0,NaN,"""La Gigue"" (Gaumont #590) is part of the ""Miss...",NaN,NaN
826016,1940971,Serpentine Dance,1902.0,NaN,"""Danse serpentine"" (Gaumont #588) is part of t...",2.0,NaN

## Pulizia Poster

In [133]:
df_posters.shape

(941597, 2)

In [134]:
df_posters.dtypes

id       int64
link    object
dtype: object

In [135]:
df_posters.head(100)
df_posters.rename(columns={'id': 'id_film'}, inplace=True)

In [136]:
df_posters["link"].fillna("https://images.fandango.com/cms/assets/5d84d010-59b1-11ea-b175-791e911be53d--rt-poster-defaultgif.gif",inplace=True)

C:\Users\andre\AppData\Local\Temp\ipykernel_2476\631055571.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_posters["link"].fillna("https://images.fandango.com/cms/assets/5d84d010-59b1-11ea-b175-791e911be53d--rt-poster-defaultgif.gif",inplace=True)

In [137]:
df_posters.isna().sum()

id_film    0
link       0
dtype: int64

In [138]:
df_posters["id_film"].duplicated().sum()

np.int64(0)

In [139]:
df_posters.shape

(941597, 2)

## Pulizia Releases

In [140]:
df_releases.shape

(1332782, 5)

In [141]:
df_releases.dtypes

id          int64
country    object
date       object
type       object
rating     object
dtype: object

In [142]:
df_releases.rename(columns={'id': 'id_film'}, inplace=True)

In [143]:
df_releases.columns

Index(['id_film', 'country', 'date', 'type', 'rating'], dtype='object')

In [144]:
rating_to_age = {
    'ATP': 0, 'PG': 10, 'U': 0, 'K-7': 7, 'TP': 10, 'IIA': 12, 'UA': 12,
    '12A': 12, 'T': 13, 'G': 0, 'N-13': 13, 'B': 12, 'M/12': 12, 'PG-13': 13,
    'PG13': 13, 'A': 18, 'K-16': 16, 'IIB': 15, 'VM14': 14, 'PG12': 12,
    'N-16': 16, 'B-15': 15, 'M/14': 14, 'M18': 18, 'R': 17, 'C18': 18,
    'K15': 15, '18A': 18, 'K-18': 18, '18PL': 18, 'C': 18, 'R-18': 18,
    'M/18': 18, 'M': 17, 'L': 18, 'S': 18, 'AL': 0, '14A': 14, 'K-12': 12,
    'K12': 12, '15A': 15, 'R-16': 16, 'AG': 0, 'D': 18, 'A-18': 18, 'R16': 16,
    'NC16': 16, 'P': 0, '18TC': 18, 'III': 18, 'VM18': 18, 'M/16': 16,
    'R21': 21, 'N-7': 7, 'M/6': 6, 'AP': 0, 'R13': 13, 'P13': 13, 'R-13': 13,
    'C16': 16, 'R18': 18, 'NR': 0, 'K-13': 13, 'X': 18, 'K18': 18,
    'N-18': 18, 'K': 0, 'SU': 0, '10A': 10, 'APTA': 0, 'R-15': 15, 'APT': 0,
    'KT/EA': 0, 'K-15': 15, 'I': 18, 'ALL': 0, 'C13': 13, '18PA': 18,
    'RP13': 13, 'Y7': 7, 'NC-16': 16, 'KN': 0, 'PG-15': 15, 'K-11': 11,
    'K-8': 8, 'PG-12': 12, '18SG': 18, 'EA': 0, 'V': 18, 'R-12': 12,
    'K-17': 17, 'B15': 15, 'AA': 18, '12PG': 12, 'K-10': 10, 'AP-12': 12,
    'TE': 13, 'R12': 12, '7-9PG': 9, '13A': 13, 'M/3': 3, 'N-15': 15,
    'KT': 0, 'SR': 18, 'K-6-4': 6, 'NC-15': 15, 'M/4': 4, 'K-14': 14,
    'NC-17': 17, 'MS12': 12, 'GP': 0, 'ZA': 0, '15PG': 15, 'R15': 15,
    'E': 0, 'RP16': 16, 'M/16Q': 16, 'II': 12, 'RC': 18, 'K-3': 3, '6A': 6,
    'PERE': 0, 'MP': 0, '7A': 7, 'N16': 16, 'K7': 7, 'TV-MA': 18,
} #from the internet

df_releases['age_min'] = df_releases['rating'].map(rating_to_age)
df_releases.fillna({'age_min': 0}, inplace=True)
df_releases["age_min"]= df_releases["age_min"].astype(int)
df_releases["age_min"] = df_releases["age_min"].replace(0, np.nan)
df_releases.drop(columns=["rating"],inplace=True)

In [145]:
df_releases.isna().sum()

id_film          0
country          0
date             0
type             0
age_min    1225161
dtype: int64

In [146]:
df_releases['date'] = pd.to_datetime(df_releases['date'],
 errors='coerce', format='%Y-%m-%d').fillna(
 pd.to_datetime(df_releases['date'],
 errors='coerce'))
 
df_releases.dtypes

id_film             int64
country            object
date       datetime64[ns]
type               object
age_min           float64
dtype: object

In [147]:
df_releases.duplicated(subset=["id_film", "country", "type", "date"]).sum()

np.int64(0)

In [148]:
df_releases.head(100)

    id_film    country       date                type  age_min
0   1000001    Andorra 2023-07-21          Theatrical      NaN
1   1000001  Argentina 2023-07-20          Theatrical      NaN
2   1000001  Australia 2023-07-19          Theatrical     10.0
3   1000001  Australia 2023-10-01             Digital     10.0
4   1000001    Austria 2023-07-20          Theatrical      NaN
..      ...        ...        ...                 ...      ...
95  1000002     Canada 2019-09-06            Premiere      NaN
96  1000002     Canada 2019-10-25  Theatrical limited      NaN
97  1000002     Canada 2019-11-01          Theatrical      NaN
98  1000002     Canada 2020-01-14             Digital      NaN
99  1000002     Canada 2020-01-28            Physical      NaN

[100 rows x 5 columns]

## Pulizia Themes

In [149]:
df_themes.rename(columns={'id': 'id_film'}, inplace=True)
df_themes.dtypes

id_film     int64
theme      object
dtype: object

In [150]:
df_themes.isna().sum()

id_film    0
theme      0
dtype: int64

In [151]:
df_themes.duplicated().sum()

np.int64(0)

In [152]:
df_themes["theme"].unique()

array(['Humanity and the world around us', 'Crude humor and satire',
       'Moving relationship stories',
       'Emotional and captivating fantasy storytelling',
       'Surreal and thought-provoking visions of life and death',
       'Quirky and endearing relationships',
       'Amusing jokes and witty satire',
       'Laugh-out-loud relationship entanglements',
       'Intense violence and sexual transgression',
       'Twisted dark psychological thriller',
       'Heartbreaking and moving family drama',
       'Enduring stories of family and marital drama',
       'Touching and sentimental family stories',
       'Intense political and terrorist thrillers',
       'Powerful stories of heartbreak and suffering',
       'Dreamlike, quirky, and surreal storytelling',
       'Challenging or sexual themes & twists',
       'Graphic violence and brutal revenge', 'Song and dance',
       'Dazzling vocal performances and musicals',
       'Captivating relationships and charming romance',
       'Dance rhythms and catchy tunes',
       'Emotional life of renowned artists',
       'Charming romances and delightful chemistry',
       'Politics and human rights', 'Epic history and literature',
       'Riveting political and presidential drama',
       'Dangerous technology and the apocalypse',
       'Political drama, patriotism, and war',
       'Monsters, aliens, sci-fi and the apocalypse',
       'Imaginative space odysseys and alien encounters',
       'Action-packed space and alien sagas',
       'Thought-provoking sci-fi action and future technology',
       "Humanity's odyssey: earth and beyond",
       'Crime, drugs and gangsters', 'Gripping, intense violent crime',
       'Epic heroes',
       'Superheroes in action-packed battles with villains',
       'Gritty crime and ruthless gangsters',
       'Violent action, guns, and crime', 'Heists and thrilling action',
       'Brutal, violent prison drama', "Kids' animated fun and adventure",
       'Action comedy and silly heroics',
       'Teen school antics and laughter',
       'Student coming-of-age challenges', 'High speed and special ops',
       'Thrillers and murder mysteries',
       'Explosive and action-packed heroes vs. villains',
       'Noir and dark crime dramas',
       'Intriguing and suspenseful murder mysteries',
       'Horror, the undead and monster classics',
       'Terrifying, haunted, and supernatural horror',
       'Creepy, chilling, and terrifying horror',
       'Gory, gruesome, and slasher horror',
       'Racism and the powerful fight for justice',
       'Suspenseful crime thrillers', 'Gothic and eerie haunting horror',
       'Erotic relationships and desire', 'Underdogs and coming of age',
       'Emotional and touching family dramas',
       'Emotional teen coming-of-age stories', 'Relationship comedy',
       'Gags, jokes, and slapstick humor', 'Funny jokes and crude humor',
       'Engaging, intense crime and casino drama',
       'Violent crime and drugs',
       'Fantasy adventure, heroism, and swordplay',
       'Historical battles and epic heroism',
       'Fairy-tale fantasy and enchanted magic',
       'Adorable animals and heartwarming families',
       'Fascinating, emotional stories and documentaries',
       'War and historical adventure', 'Nazis and World War II',
       'Military combat and heroic soldiers', 'Bravery in War',
       'Adrenaline-fueled action and fast cars',
       'Intense combat and martial arts', 'Westerns',
       'Wild west outlaws and gunfights',
       'Western frontier dramas with a touch of humor',
       'Emotional LGBTQ relationships', 'Passion and romance',
       'Holiday joy and heartwarming Christmas',
       'Catchy songs and hilarious musical comedy',
       'Sci-fi horror, creatures, and aliens', 'Faith and religion',
       'Epic adventure and breathtaking battles',
       'Tragic sadness and captivating beauty',
       'Disastrous voyages and heroic survival',
       'Underdog fighting and boxing stories',
       'Air pilot heroism and survival',
       'Exciting spy thrillers with tense intrigue',
       'Sci-fi monster and dinosaur adventures',
       'Chilling experiments and classic monster horror',
       'Captivating vision and Shakespearean drama',
       'Powerful poetic and passionate drama', 'Spooky, scary comedy',
       'Legendary musicians and stardom',
       'Religious faith, sin, and forgiveness', 'Bloody vampire horror',
       'Inspiring sports underdog stories',
       'Survival horror and zombie carnage',
       'Extreme gory horror and cannibalism',
       'Lavish dramas and sumptuous royalty',
       'Faith and spiritual journeys',
       'Politics, propaganda, and political documentaries',
       'Teen friendship and coming-of-age', 'Bollywood emotional dramas'],
      dtype=object)

## Pulizia Studios

In [153]:
df_studios.shape

(679283, 2)

In [154]:
df_studios.rename(columns={'id': 'id_film'}, inplace=True)
df_studios.dtypes

id_film     int64
studio     object
dtype: object

In [155]:
df_studios.isna().sum()

id_film     0
studio     10
dtype: int64

In [156]:
df_studios.loc[df_studios['studio'].isna(), "studio"] = "Unknown"

In [157]:
df_studios.duplicated().sum()

np.int64(212)

In [158]:
df_studios=df_studios.drop_duplicates(subset=["id_film","studio"],keep="first")
df_studios.shape

(679071, 2)

## Pulizia RottenTomatoes Reviews

In [159]:
df_tomatoes.shape

(1129887, 9)

In [160]:
df_tomatoes.dtypes

rotten_tomatoes_link    object
movie_title             object
critic_name             object
top_critic                bool
publisher_name          object
review_type             object
review_score            object
review_date             object
review_content          object
dtype: object

In [161]:
#change review_date from str to date
df_tomatoes["review_date"]=pd.to_datetime(df_tomatoes["review_date"], format="%Y-%m-%d", errors="coerce")
df_tomatoes.dtypes

rotten_tomatoes_link            object
movie_title                     object
critic_name                     object
top_critic                        bool
publisher_name                  object
review_type                     object
review_score                    object
review_date             datetime64[ns]
review_content                  object
dtype: object

In [162]:
df_tomatoes["link"] = "https://www.rottentomatoes.com/" + df_tomatoes["rotten_tomatoes_link"].astype(str)
df_tomatoes

,rotten_tomatoes_link,movie_title,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,link
0,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...,https://www.rottentomatoes.com/m/0814255
1,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff...",https://www.rottentomatoes.com/m/0814255
2,m/0814255,Percy Jackson & the Olympians: The Lightning T...,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...,https://www.rottentomatoes.com/m/0814255
3,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...,https://www.rottentomatoes.com/m/0814255
4,m/0814255,Percy Jackson & the Olympians: The Lightning T...,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...,https://www.rottentomatoes.com/m/0814255
...,...,...,...,...,...,...,...,...,...,...
1129882,m/zulu_dawn,Zulu Dawn,Chuck O'Leary,False,Fantastica Daily,Rotten,2/5,2005-11-02,NaN,https://www.rottentomatoes.com/m/zulu_dawn
1129883,m/zulu_dawn,Zulu Dawn,Ken Hanke,False,"Mountain Xpress (Asheville, NC)",Fresh,3.5/5,2007-03-07,"Seen today, it's not only a startling indictme...",https://www.rottentomatoes.com/m/zulu_dawn
1129884,m/zulu_dawn,Zulu Dawn,Dennis Schwartz,False,Dennis Schwartz Movie Reviews,Fresh,B+,2010-09-16,A rousing visual spectacle that's a prequel of...,https://www.rottentomatoes.com/m/zulu_dawn
1129885,m/zulu_dawn,Zulu Dawn,Christopher Lloyd,False,Sarasota Herald-Tribune,Rotten,3.5/5,2011-02-28,"A simple two-act story: Prelude to war, and th...",https://www.rottentomatoes.com/m/zulu_dawn
1129886,m/zulu_dawn,Zulu Dawn,Brent McKnight,False,The Last Thing I See,Rotten,C,2020-07-09,Rides the line between being a pure artifact o...,https://www.rottentomatoes.com/m/zulu_dawn

In [163]:
df_tomatoes = df_tomatoes.drop(columns=["rotten_tomatoes_link"])
df_tomatoes.head()

,movie_title,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content,link
0,Percy Jackson & the Olympians: The Lightning T...,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...,https://www.rottentomatoes.com/m/0814255
1,Percy Jackson & the Olympians: The Lightning T...,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff...",https://www.rottentomatoes.com/m/0814255
2,Percy Jackson & the Olympians: The Lightning T...,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...,https://www.rottentomatoes.com/m/0814255
3,Percy Jackson & the Olympians: The Lightning T...,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...,https://www.rottentomatoes.com/m/0814255
4,Percy Jackson & the Olympians: The Lightning T...,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...,https://www.rottentomatoes.com/m/0814255

### normalizing review data (all scores x will be translated in x/5)

In [164]:
df_tomatoes[~df_tomatoes['review_score'].str.contains('/', na=False)]['review_score'].unique()

array([nan, 'B', 'C', 'C-', 'B-', 'C+', 'D+', 'B+', 'A-', 'A', 'D-', 'F',
       'D', '5', '4', '7', '3', '10', '2', '1', '8', '0', '6', '9', '25',
       '88', '48', '45', '24', '35', 'A  -', '46', '90', '75', '89',
       'C  -', '34', '68', '95', '920', '910', '14', '72', '67', '80',
       '70', '77'], dtype=object)

In [165]:
#first of all normalizing letter to values
df_tomatoes.loc[df_tomatoes["review_score"] == "A", "review_score"] = "5/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "A  -", "review_score"] = "4.75/5" #one record
df_tomatoes.loc[df_tomatoes["review_score"] == "A-", "review_score"] = "4.75/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "B+", "review_score"] = "4.25/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "B", "review_score"] = "4/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "B-", "review_score"] = "3.75/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "C+", "review_score"] = "3.25/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "C", "review_score"] = "3/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "C-", "review_score"] = "2.75/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "C  -", "review_score"] = "2.75/5" #one record
df_tomatoes.loc[df_tomatoes["review_score"] == "D+", "review_score"] = "1.25/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "D", "review_score"] = "2/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "D-", "review_score"] = "1.75/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "E", "review_score"] = "1/5"
df_tomatoes.loc[df_tomatoes["review_score"] == "F", "review_score"] = "0/5"
df_tomatoes["review_score"].unique()

array([nan, '3.5/5', '1/4', '4/5', '3/5', '2/4', '2/5', '2.5/4', '3/4',
       '2.75/5', '3.75/5', '2.5/5', '5.5/10', '1/5', '3.25/5', '1.25/5',
       '1.5/4', '6.5/10', '3/10', '1.5/5', '4/10', '7/10', '6/10',
       '4.25/5', '5/5', '4.75/5', '4.5/5', '5.78/10', '3.5/4', '9/10',
       '8.5/10', '4/4', '83/100', '8/10', '92/100', '82/100', '84/100',
       '10/10', '1.75/5', '0/5', '0.5/4', '5/10', '2/10', '2/6', '0.5/5',
       '0/4', '76/100', '87/100', '74/100', '86/100', '81/100', '56/100',
       '78/100', '2.25/5', '8.8/10', '0/10', '44/100', '2.75/4', '2.4/5',
       '8.6/10', '79/100', '68/100', '80/100', '90/100', '66/100',
       '91/100', '0.3/5', '9.2/10', '2.7/5', '57/100', '4/6', '3/6',
       '73/100', '42/100', '65/100', '7.5/10', '4.5/10', '5/6', '1/6',
       '70/100', '3.5/10', '71/100', '0.1/5', '3.25/10', '89/100',
       '40/100', '64/100', '62/100', '1/10', '37/100', '49/100', '60/100',
       '3.3/5', '77/100', '5.25/10', '1.4/4', '75/100', '1.5/6', '85/100',
       '4.25/10', '47/100', '6/8', '52/100', '63/100', '50/100', '41/100',
       '46/100', '6.95/10', '53/100', '9.5/10', '59/100', '43/100',
       '9.45/10', '45/100', '69/100', '7.25/10', '5.85/10', '9.88/10',
       '39/100', '0.13/1', '8.25/10', '5.75/10', '6.1/10', '6.8/10',
       '8.9/10', '8.75/10', '2.5/10', '5.9/10', '4.2/10', '7.35/10',
       '4.6/10', '6.75/10', '4.90/10', '4.827/10', '2/2', '58/100',
       '4.75/10', '3.4/10', '88/100', '5.48/10', '9.16/10', '3.4/4',
       '3.7/10', '6.765/10', '67/100', '34/100', '51/100', '3.4/5',
       '72/100', '93/100', '5', '95/95', '98/100', '94/100', '99/100',
       '4', '55/100', '61/100', '35/100', '95/100', '1/3', '5/8', '7',
       '4.2/5', '3', '30/100', '54/100', '48/100', '18/100', '10',
       '25/100', '7/5', '7.4/10', '2', '6.2/10', '5.12/10', '5/100', '1',
       '0.75/5', '8', '100/100', '2.8/4', '2.25/4', '31/100', '2.4/4',
       '32/100', '3.8/5', '8.3/10', '8.4/10', '5.3/10', '0/100', '0.2/5',
       '8.7/10', '2.2/5', '2.3/5', '3.2/5', '2.8/5', '2.75/3', '4.85/10',
       '3.5/6', '3.25/4', '0.5/10', '1.75/4', '28/100', '9.25/10',
       '5.80/10', '6.25/10', '7.2/10', '6.9/10', '1.2/5', '8.35/10',
       '6.4/10', '7/11', '8.70/10', '9.75/10', '1.21/10', '1.35/5',
       '23/100', '38/100', '6.3/10', '8.85/10', '7.3/10', '7.15/10',
       '1.25/4', '3.9/10', '4.21/10', '9.35/10', '2.75/10', '8.76/10',
       '7.7/10', '7.75/10', '5.15/10', '7.85/10', '1.8/5', '0', '6.45/10',
       '5.95/10', '8.1/10', '3.7/5', '7.9/10', '9.9/10', '13/20', '6',
       '2.83/5', '17/20', '8.74/10', '9', '7.8/10', '5.8311/10', '47/50',
       '3.20/10', '6.65/10', '5.88/10', '19/100', '2.5/3', '15/100',
       '8.621/10', '16/20', '5.8/10', '1.5/10', '8.50/10', '5.65/10',
       '10.50/20', '9.19/10', '4.4/10', '5.6/10', '14.5/20', '4.1/5',
       '8.05/10', '0/6', '1.6/5', '3.1/5', '6.85/10', '4.35/10', '9.1/10',
       '8.88/10', '6.6/10', '6.7/10', '5.4/10', '20/20', '8.2/10',
       '16.5/20', '7.1/10', '5.7/10', '11/20', '8.95/10', '3.75/10',
       '15/20', '3.6/5', '7.6/10', '5.9737991/10', '18.5/20', '14/20',
       '7.05/10', '18/20', '9.86/10', '4.8/10', '4.7/10', '2.74/10',
       '4.9/10', '26/100', '2.12/5', '5.2/10', '7.96/10', '21/100',
       '6.9921/10', '4.5/4', '7.892/10', '5.5/5', '1/54', '1.2/10',
       '8.89/10', '33/100', '8.99/10', '5.5/20', '8.10/10', '6.68/10',
       '13/100', '2.9/10', '5.61/10', '4.65/10', '8/20', '9.12/10', '3/3',
       '5.49/10', '20/100', '6.78/10', '10/20', '0.02/5', '3.8/10',
       '8.65/10', '5.1/10', '9/5', '1.7/5', '25', '8.7328/10',
       '7.00122/10', '9.851/10', '8.251/10', '5/20', '7.57/10', '12/20',
       '2.1/5', '9.5/20', '10/100', '5.51/10', '1.4/5', '2.6/6', '9.4/10',
       '4.8/5', '4.45/10', '4.65/5', '2.6/5', '3.15/5', '6.98/10',
       '4.7/5', '4.1/10', '3.5/3', '4.4/5', '9.3/10', '4.3/5', '3.9/5',
       '2.20282652/10', '3.75/4', '3.3/10', '11.5/20', '7.5/20',
       '8.53899/10', '6/13', '2.11/5', '9.7/10', '2.6/10', '0.7221/10',
       '3.76/5', '2.95/10', '6.15/10', '7.5314585/10', '8.15/10',
       '9.85/10', '97/100', '7.83/10', '3.2121/10', '8.55/10',
       '2.282303/10', '88', '1.5/2', '4.21382343/10', '8/100', '17.5/20',
       '1.24/5', '4.3/10', '2.7/10', '4.521/10', '6.0001/10',
       '4.143641/10', '9.15/10', '48', '4.05524/10', '8/5', '3/100',
       '3.83412437/10', '9.6/10', '9.79/10', '7.21/10', '9.5/5', '3.2/10',
       '7.696/10', '5.872/10', '9.50/20', '5.1921/10', '2.892521821/10',
       '0.81/1', '27/100', '6.35/10', '2.9/5', '9.74/10', '9.33/10',
       '7.02/10', '2.1/10', '7.89/10', '2.50/5', '9.21/10', '5.57/10',
       '19/20', '9.8/10', '8.32/10', '1/1', '5.9821/10', '8.385/10',
       '0.5/5.5', '45', '7.95/10', '6.09/10', '1.9/10', '3.55/10',
       '7.45/10', '7.62121/10', '1.9/5', '3.515/10', '15.5/20', '3.85/10',
       '8.72/10', '35/4', '5.5/6', '36/100', '9.1221/10', '9.65/10',
       '4.70/10', '2.2/10', '7.61/10', '2.3/4', '6.4821/10', '7.3821/10',
       '8.3721/10', '5.44/10', '8.92/10', '7.49/10', '8.225/10', '0.25/4',
       '1.5242228/10', '5.56/10', '9/20', '24/100', '7.01/10', '9.67/10',
       '7.2234238/10', '6.00024/10', '7.111113314/10', '8.21/10',
       '5.21/10', '79/80', '9.145/10', '9.865/10', '4.95/10', '5.6642/10',
       '9/100', '6.875/10', '0.66/10', '1.2/4', '5.8943/10', '3.99/10',
       '13.5/20', '61/00', '5.72/10', '1.3/5', '0.05/4', '4.6/5',
       '8.57/10', '24', '0/1000', '5.35/10', '29/100', '1.9528/10', '35',
       '7.65/10', '5.55/10', '2.5/20', '69/70', '9.26/10', '8.735/10',
       '6.1121/10', '6.0000001/10', '2/8', '9.78/10', '5.45/10',
       '14.50/20', '6.26/10', '2.85/5', '2.6/4', '7.218/10', '0.6/1',
       '3.021/10', '7.10/10', '0.96/10', '8.666/10', '3/40', '0.82/10',
       '7.98/10', '5.5542/10', '8.901/10', '2.55/5', '7.22/10', '5.70/10',
       '7.04/10', '2.4/10', '5.89521/10', '2.8/10', '7.3856/10',
       '8.899327/10', '1.1/2', '8.2621/10', '7.212121/10', '4.89215/10',
       '9.89/10', '2.212521/10', '22/100', '5.6521/10', '8.87/10',
       '3.1/10', '4/5.5', '4.95/5', '8.19/10', '9.552/10', '7/20',
       '4.211/10', '4/3.5', '46', '4.9837/10', '9.38/10', '5.284849/10',
       '8.67/10', '6.9621/10', '2.5/50', '2.255/5', '90', '75', '8.61/10',
       '3.5/5.5', '5.81/10', '66/70', '3.222423/10', '4.2112/10',
       '1.82/10', '6.000003231/10', '3.76/10', '5.76/10', '2/54', '0.8/5',
       '6/11', '8.458/10', '2.89/5', '5.8921/10', '8.496/10', '2.3/10',
       '0.21/10', '4.51/10', '9.76/10', '59/60', '0.9/10', '3.65/5',
       '6/6', '6.7/8', '9.46/10', '8.45/10', '8.26/10', '1.85/10',
       '0.75/10', '4.89/10', '6.55/10', '1.62/5', '0.85/10', '9.121/10',
       '9.6421/10', '8.5788222/10', '3.45/5', '96/100', '67/10',
       '7.2621/10', '2/3', '5.23/10', '7.79/10', '9.1421/10', '87/10',
       '12.50/20', '7.825/10', '8.921/10', '6.24/10', '8.124/10',
       '8.01/10', '4.56/10', '1.5/3', '4.79/10', '8.16/10', '0.59/1',
       '2.7/4', '1.1/5', '89', '4.55/10', '2.5/6', '9.8521/10',
       '3.7822391/10', '7.2521/10', '7.18321/10', '3.6/4', '8.42/10',
       '9.73889/10', '12/100', '7.44/10', '8.5/5', '6/20', '6.01/10',
       '34', '8.98/10', '7.48/10', '3.65/10', '7.0921/10', '3.35/5',
       '1.4/10', '4/0', '6.96/10', '7.001/10', '5.22/10', '1.8/4',
       '16/100', '9.889/10', '14/100', '8.999/10', '9.188/10', '7.021/10',
       '4.42/10', '8.212121/10', '3.6/10', '0.7765823/10', '8.425/10',
       '9.48/10', '9.30/10', '4.86/10', '7.5211/10', '5/11', '8.71/10',
       '68', '3.7521/10', '4.021/10', '8.881/10', '5.10/10', '3/5.5',
       '95', '5.623433899/10', '0.65/10', '7/8', '9.18/10', '5.82/10',
       '5.212/10', '5.895/10', '6.8666/10', '920', '3.0782/10', '2.95/5',
       '4.22/10', '0.13/5', '2.65/10', '0.4/5', '8.453895/10', '6.001/10',
       '9.52/10', '6.16/10', '8.9521/10', '9.85621/10', '76/10',
       '0.664363/10', '9.51/10', '5.02120621/10', '3.2/4', '2/20',
       '5.1221/10', '12.5/20', '8.327/10', '1.88/10', '11/100', '75/10',
       '8.39421/10', '910', '9.95/10', '2/9', '8.199/10', '8.485/10',
       '7.621/10', '5.232121/10', '5.67/10', '8.24/10', '39/40', '3/5.4',
       '2/100', '7.94215/10', '9.68/10', '6/5', '6.19/10', '25/4',
       '4.5/6', '9.021/10', '8.32321/10', '7.87/10', '5.50/10',
       '8.2521/10', '2.1/2', '5.05/10', '0.6/10', '3.5/20', '9.14/10',
       '7.42/10', '9.2021/10', '6.05/10', '4/8', '3.54/5', '14',
       '9.49/10', '6.97/10', '4.9834326/10', '10/90', '72', '67', '45/5',
       '7.0155/10', '3.3/4', '6.89/10', '9.921/10', '80', '0.666/4',
       '2.55/4', '1.1/10', '3.5/18', '73/10', '8.30/10', '8.56/10',
       '6.8843/10', '6.00001/10', '4.364221/10', '4.293382/10', '6.84/10',
       '9.01/10', '8.68/10', '9.649821/10', '3/45', '8.692121/10', '70',
       '6.02/10', '0.58/1', '5.4221/10', '7.12/10', '8.1921/10',
       '9.87/10', '8.84/10', '9.20/10', '0.8/10', '8.9621/10', '3/20',
       '0.52/1', '8.3/100', '4/100', '1.75/10', '1.8/10', '4.0001/10',
       '77', '5.9999/10', '9.66/10', '9.99/10', '5.751/10', '7.55/10',
       '5.01/10', '3.56339/10', '4.558/10', '7.94/10', '3.5/44',
       '8.765/10', '4.35/5', '21/24', '6.02121/10', '1/2', '7.4921/10',
       '5.046/10', '9.56/10'], dtype=object)

In [166]:
df_tomatoes[['numerator', 'denominator']] = df_tomatoes['review_score'].str.split('/', expand=True)
df_tomatoes['numerator'] = df_tomatoes['numerator'].fillna(-1)
df_tomatoes['denominator'] = df_tomatoes['denominator'].fillna(-1)

In [167]:
df_tomatoes['numerator'] = df_tomatoes['numerator'].astype(float)
df_tomatoes['denominator'] = df_tomatoes['denominator'].astype(float)

In [168]:
df_tomatoes.loc[df_tomatoes['numerator'] > df_tomatoes['denominator'], ['numerator', 'denominator']] = -1
# calculate all in /5
df_tomatoes['rating'] = np.where(df_tomatoes['numerator'] == -1, -1, (df_tomatoes['numerator'] / df_tomatoes['denominator']) * 5)

In [169]:
df_tomatoes = df_tomatoes.drop(columns=["numerator", "denominator", "review_score"])

In [170]:
df_tomatoes["rating"] = df_tomatoes["rating"].replace(-1, np.nan)

In [171]:
df_tomatoes.isna().sum()

movie_title            0
critic_name        18521
top_critic             0
publisher_name         0
review_type            0
review_date            0
review_content     65778
link                   0
rating            307546
dtype: int64

In [172]:
df_tomatoes.shape

(1129887, 9)

In [173]:
df_tomatoes.dtypes

movie_title               object
critic_name               object
top_critic                  bool
publisher_name            object
review_type               object
review_date       datetime64[ns]
review_content            object
link                      object
rating                   float64
dtype: object

In [174]:
subset = ["movie_title", "critic_name", "publisher_name", "review_type", "review_content", "review_date"]
df_tomatoes = df_tomatoes.drop_duplicates(subset=subset,keep="first")
df_tomatoes.shape

(1010313, 9)

## Pulizia Oscars

In [175]:
df_oscars

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
10884,2023,2024,96,WRITING (Original Screenplay),Written by Celine Song,Past Lives,False
10885,2023,2024,96,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10886,2023,2024,96,HONORARY AWARD,"To Angela Bassett, who has inspired audiences ...",NaN,True
10887,2023,2024,96,HONORARY AWARD,"To Mel Brooks, for his comedic brilliance, pro...",NaN,True
10888,2023,2024,96,HONORARY AWARD,"To Carol Littleton, whose commitment to her cr...",NaN,True

In [176]:
df_oscars["year_film"]=pd.to_datetime(df_oscars["year_film"], format="%Y", errors="coerce")
df_oscars["year_ceremony"]=pd.to_datetime(df_oscars["year_ceremony"], format="%Y", errors="coerce")

In [177]:
df_oscars.shape

(10889, 7)

In [178]:
df_oscars.dtypes

year_film        datetime64[ns]
year_ceremony    datetime64[ns]
ceremony                  int64
category                 object
name                     object
film                     object
winner                     bool
dtype: object

In [179]:
subset_oscars=["year_film", "year_ceremony", "ceremony", "category", "name", "film"]
df_oscars = df_oscars.drop_duplicates(subset=subset_oscars,keep="first")

In [180]:
df_oscars[df_oscars[["name", "film"]].isna().all(axis=1)]

,year_film,year_ceremony,ceremony,category,name,film,winner
10513,2020-01-01,2021-01-01,93,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10635,2021-01-01,2022-01-01,94,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10759,2022-01-01,2023-01-01,95,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True
10885,2023-01-01,2024-01-01,96,JEAN HERSHOLT HUMANITARIAN AWARD,NaN,NaN,True

In [181]:
output_dir = "clean_datasets"
os.makedirs(output_dir, exist_ok=True)

df_actors.to_csv(os.path.join(output_dir, "df_actors.csv"), index=False)
df_countries.to_csv(os.path.join(output_dir, "df_countries.csv"), index=False)
df_crew.to_csv(os.path.join(output_dir, "df_crew.csv"), index=False)
df_released_movies.to_csv(os.path.join(output_dir, "df_released_movies.csv"), index=False)
df_unreleased_movies.to_csv(os.path.join(output_dir, "df_unreleased_movies.csv"), index=False)
df_movies.to_csv(os.path.join(output_dir, "df_movies.csv"), index=False)
df_languages.to_csv(os.path.join(output_dir, "df_languages.csv"), index=False)
df_posters.to_csv(os.path.join(output_dir, "df_posters.csv"), index=False)
df_releases.to_csv(os.path.join(output_dir, "df_releases.csv"), index=False)
df_themes.to_csv(os.path.join(output_dir, "df_themes.csv"), index=False)
df_genres.to_csv(os.path.join(output_dir, "df_genres.csv"), index=False)
df_studios.to_csv(os.path.join(output_dir, "df_studios.csv"), index=False)
df_tomatoes.to_csv(os.path.join(output_dir, "df_tomatoes.csv"), index=False)
df_oscars.to_csv(os.path.join(output_dir, "df_oscars.csv"), index=False)